<a href="https://colab.research.google.com/github/steenbergen/DeepLearn/blob/main/DataWrangle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading Data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
whr23 = pd.read_csv('/content/drive/My Drive/Colab Notebooks/WHR2023.csv')
whr23

,Country name,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,Continent
0,Finland,7.804,0.036,7.875,7.733,10.792,0.969,71.150,0.961,-0.019,0.182,1.778,1.888,1.585,0.535,0.772,0.126,0.535,2.363,Europe
1,Denmark,7.586,0.041,7.667,7.506,10.962,0.954,71.250,0.934,0.134,0.196,1.778,1.949,1.548,0.537,0.734,0.208,0.525,2.084,Europe
2,Iceland,7.530,0.049,7.625,7.434,10.896,0.983,72.050,0.936,0.211,0.668,1.778,1.926,1.620,0.559,0.738,0.250,0.187,2.250,Europe
3,Israel,7.473,0.032,7.535,7.411,10.639,0.943,72.697,0.809,-0.023,0.708,1.778,1.833,1.521,0.577,0.569,0.124,0.158,2.691,Asia
4,Netherlands,7.403,0.029,7.460,7.346,10.942,0.930,71.550,0.887,0.213,0.379,1.778,1.942,1.488,0.545,0.672,0.251,0.394,2.110,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,Congo (Kinshasa),3.207,0.095,3.394,3.020,7.007,0.652,55.375,0.664,0.086,0.834,1.778,0.531,0.784,0.105,0.375,0.183,0.068,1.162,Africa
133,Zimbabwe,3.204,0.061,3.323,3.084,7.641,0.690,54.050,0.654,-0.046,0.766,1.778,0.758,0.881,0.069,0.363,0.112,0.117,0.905,Africa
134,Sierra Leone,3.138,0.082,3.299,2.976,7.394,0.555,54.900,0.660,0.105,0.858,1.778,0.670,0.540,0.092,0.371,0.193,0.051,1.221,Africa
135,Lebanon,2.392,0.044,2.479,2.305,9.478,0.530,66.149,0.474,-0.141,0.891,1.778,1.417,0.476,0.398,0.123,0.061,0.027,-0.110,Asia
136,Afghanistan,1.859,0.033,1.923,1.795,7.324,0.341,54.712,0.382,-0.081,0.847,1.778,0.645,0.000,0.087,0.000,0.093,0.059,0.976,Asia

# Basic Data Attributes

# Selecting Cells
Can be done using **.iloc** and **loc**.

In [5]:
whr23.iloc[0]

Country name                                  Finland
Ladder score                                    7.804
Standard error of ladder score                  0.036
upperwhisker                                    7.875
lowerwhisker                                    7.733
Logged GDP per capita                          10.792
Social support                                  0.969
Healthy life expectancy                         71.15
Freedom to make life choices                    0.961
Generosity                                     -0.019
Perceptions of corruption                       0.182
Ladder score in Dystopia                        1.778
Explained by: Log GDP per capita                1.888
Explained by: Social support                    1.585
Explained by: Healthy life expectancy           0.535
Explained by: Freedom to make life choices      0.772
Explained by: Generosity                        0.126
Explained by: Perceptions of corruption         0.535
Dystopia + residual                             2.363
Continent                                      Europe
Name: 0, dtype: object

In [7]:
whr23.iloc[:,0:2]

         Country name  Ladder score
0             Finland         7.804
1             Denmark         7.586
2             Iceland         7.530
3              Israel         7.473
4         Netherlands         7.403
..                ...           ...
132  Congo (Kinshasa)         3.207
133          Zimbabwe         3.204
134      Sierra Leone         3.138
135           Lebanon         2.392
136       Afghanistan         1.859

[137 rows x 2 columns]

In [10]:
whr23.iloc[2,1]

7.53

In [14]:
whr23.loc[Country_name = "France"]

SyntaxError: ignored